eCommerceTutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include("user.urls"), name="user"),
    path('order/', include("order.urls")),
]

if settings.DEBUG:  # ! hata verse bile hata değil çalışıyour pylance bugu
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name="about"),
    path('references', views.references, name="references"),
    path('contact', views.contact, name="contact"),
    path('category/<int:id>/<str:slug>',
         views.category_products, name="category_products"),
    path('product/<int:id>/<str:slug>',
         views.product_detail, name="product_detail"),
    path('addcomment/<int:id>', views.add_comment, name="add_comment"),
    path('search/', views.search, name="search"),
    path('search_auto/', views.product_auto_search, name="auto_search"),
    path('logout/', views.logout_view, name="logout"),
    path('login/', views.login_view, name="login"),
    path('register/', views.register_view, name="register"),
]

order/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="order_index"),
    path("addtobasket/<int:id>", views.addtobasket, name="addtobasket"),
    path("deletetobasket/<int:id>", views.deletetobasket, name="deletetobasket"),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
    path('user_orders', views.user_orders, name="user_orders"),
    path('user_order_details/<int:id>', views.user_orders_details,
         name="user_order_details"),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product
from django.contrib.auth.models import User
from django.forms import ModelForm


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def price(self):
        return (self.product.price)


class Order(models.Model):
    STATUS = (
        ("New", "New"),
        ("Accepted", "Accepted"),
        ("Preparing", "Preparing"),
        ("OnShipping", "OnShipping"),
        ("Completed", "Completed"),
        ("Canceled", "Canceled"),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone = models.CharField(max_length=30)
    address = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    total = models.FloatField()
    status = models.CharField(max_length=30, choices=STATUS)
    ip = models.CharField(max_length=30, blank=True)
    adminnote = models.CharField(max_length=30, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ["first_name", "last_name",
                  "address", "phone", "city", "country"]


class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.contrib import messages
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from product.models import Category, Product
from .models import Basket, Order, OrderForm, OrderProduct
from django.contrib.auth.decorators import login_required
from home.models import UserProfile
from django.utils.crypto import get_random_string


def index(request):
    category = Category.objects.all()
    basket = Basket.objects.filter(user_id=request.user.id)
    context = {
        "categories": category,
        "baskets": basket,
    }
    return render(request, "shopping_cart.html", context)


@login_required(login_url="/login")
def addtobasket(request, id):
    checkBasket = Basket.objects.filter(product_id=id)
    control = True if checkBasket else False
    data = checkBasket[0] if control else Basket()
    data.user = request.user
    data.product = Product.objects.get(pk=id)
    if request.method == "POST":
        if control:
            data.quantity += int(request.POST["quantity"])
        else:
            data.quantity = int(request.POST["quantity"])
    elif id:
        data.quantity = data.quantity + 1 if control else 1

    amount = Product.objects.get(pk=id).amount
    if data.quantity > amount:
        data.quantity = amount
    data.save()
    request.session["basketCount"] = Basket.objects.filter(
        user_id=request.user.id).count()
    request.session["basketPrice"] = sum(
        [i.amount for i in Basket.objects.filter(user_id=request.user.id)])
    return redirect("order_index")


def deletetobasket(request, id):
    Basket.objects.filter(id=id).delete()
    request.session["basketCount"] = Basket.objects.filter(
        user_id=request.user.id).count()
    request.session["basketPrice"] = sum(
        [i.amount for i in Basket.objects.filter(user_id=request.user.id)])
    return redirect("order_index")


def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = Basket.objects.filter(user_id=current_user.id)
    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity

    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        # return HttpResponse(request.POST.items())
        if form.is_valid():
            # Send Credit card to bank,  If the bank responds ok, continue, if not, show the error
            # ..............

            data = Order()
            # get product quantity from form
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user = current_user
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()  # random cod
            data.code = ordercode
            data.save()

            for rs in shopcart:
                detail = OrderProduct()
                detail.order = data  # Order Id
                detail.product = rs.product
                detail.user = current_user
                detail.quantity = rs.quantity
                detail.price = rs.product.price
                detail.amount = rs.amount
                detail.save()
                # ***Reduce quantity of sold product from Amount of Product

                product = Product.objects.get(id=rs.product_id)
                product.amount -= rs.quantity
                product.save()

            # Clear & Delete shopcart
            Basket.objects.filter(user_id=current_user.id).delete()
            request.session['basketCount'] = 0
            messages.add_message(
                request, messages.SUCCESS, "Your Order has been completed. Thank you ")
            return render(request, 'Order_Completed.html', {'ordercode': ordercode, 'categories': category})
        else:
            messages.add_message(request, messages.WARNING, str(form.errors))
            return HttpResponseRedirect("/order/orderproduct")

    form = OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {
        'shopcart': shopcart,
        'categories': category,
        'total': total,
        'form': form,
        'profile': profile,
    }
    return render(request, 'Order_Form.html', context)


def user_orders(request):
    context = {
        "categories": Category.objects.all(),
        "orders": Order.objects.filter(user_id=request.user.id)
    }
    return render(request, "user_orders.html", context)


def user_orders_details(request, id):
    context = {
        "categories": Category.objects.all(),
        "order": Order.objects.filter(user_id=request.user.id, id=id),
        "order_items": OrderProduct.objects.filter(order_id=id),
    }
    return render(request, "user_order_details.html", context)

order/templates/Order_Completed.html
{% extends 'homebase.html' %}

{% block title %} Order Complated {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Complated</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order Complated</h3>
                        </div>
                        <hr>
                        <h2>Dear  {{ user.first_name }} {{  user.last_name }}</h2>
                        <hr>
                        <h3>Your order is completed</h3>
                        <h3>Order Code : {{ ordercode }}</h3>
                        <h3>Thank You</h3>
                        <hr>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

order/templates/Order_Form.html
{% extends 'homebase.html' %}
{% block title %} Order Page {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Page</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div  class="row">
                <Form action="" method="post">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <div class="billing-details">

                            <div class="section-title">
                                <h4 class="title">Shipping Details</h4>
                            </div>
                            <p><label for="id_first_name">First name:</label>
                                <input type="text" name="first_name"  value="{{ user.first_name }}" class="input" maxlength="10" required id="id_first_name"></p>
                            <p><label for="id_last_name">Last name:</label>
                                <input type="text" name="last_name"  value="{{ user.last_name }}" class="input" maxlength="10" required id="id_last_name"></p>
                            <p><label for="id_address">Address:</label>
                                <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150" id="id_address"></p>
                            <p><label for="id_phone">Phone:</label>
                                <input type="text" name="phone"  value="{{ profile.phone }}"  class="input" maxlength="20" id="id_phone"></p>
                            <p><label for="id_city">City:</label>
                                <select name="city" class="input" id="id_city">
                                    <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                    <option value="İstanbul">Istanbul</option>
                                    <option value="Ankara">Ankara</option>
                                    <option value="İzmir">Izmir</option>
                                    <option value="Bursa">Bursa</option>
                                    <option value="Konya">Konya</option>
                                    <option value="Yozgat">Yozgat</option>
                                </select></p>
                            <p><label for="id_first_name">Country :</label>
                                <input type="text" name="country" class="input" id="id_country" value="{{ profile.country }}"></p>
                            <div class="pull-right">
                                <button  type="submit" class="primary-btn">Complete Order</button>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="shiping-methods">
                            <div class="section-title">
                                <h4 class="title">Payment Information</h4>
                            </div>
                            <p><label for="id_first_name">Total: {{ total }} USD </label>
                                <input type="text" name="total" class="input" readonly value="${{ total }}"></p>
                            <p><label for="id_first_name">Credit Card Holder</label>
                                <input type="text" name="holder" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Card Number</label>
                                <input type="text" name="number" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Exp Date/Year</label>
                                <input type="text" name="ecpdate" class="input"  placeholder="mm/yy"></p>
                            <p><label for="id_first_name">Security Number</label>
                                <input type="text" name="secnumber" class="input"  value=""></p>
                        </div>
                    </div>

                </Form>

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Shopcart Product List</h3>
                        </div>
                                                <table class="shopping-cart-table table">
                            <thead>
                            <tr>
                                <th></th>
                                <th>Product</th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Quantity</th>
                                <th class="text-center">Total</th>
                                <th class="text-right"></th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for rs in shopcart %}
                                <tr>
                                    <td class="thumb">
                                        
                                        <img src="{{rs.product.image.url}}" alt="">
                                        

                                    </td>
                                    <td class="details">
                                        <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">{{rs.product}} </a>  </td>
                                    <td class="price text-center"><strong>
                                  
                                            {{ rs.product.price }} 
                                        
                                    </strong></td>
                                    <td class="qty text-center"><strong>{{rs.quantity}}</strong></td>
                                    <td class="total text-center"><strong class="primary-color">$
                                      
                                            {{ rs.amount }} 
                                        
                                    </strong></td>
                                    <td class="text-right"><a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete ! Are you sure?')" class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                                </tr>

                            {% endfor %}

                            </tbody>
                            <tfoot>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>SUBTOTAL</th>
                                <th colspan="2" class="sub-total">{{ total }}</th>
                            </tr>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>SHIPING</th>
                                <td colspan="2">Free Shipping</td>
                            </tr>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>TOTAL</th>
                                <th colspan="2" class="total">{{ total }} </th>
                            </tr>
                            </tfoot>
                        </table>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

order/templates/shopping_cart.html
{% extends 'homebase.html' %} {% load static %}
<!-- prettier-ignore -->
{% block title %} İletişim-{{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %}{{ setting.description }} {% endblock %}

{% block head %}
<!-- prettier-ignore -->
<link type="image/png" rel="icon" sizes="96x96" href="{{ setting.icon.url }}" />
{% endblock %}

<!-- prettier-ignore -->
{% block sidebar %}
    {% include 'sidebar.html' %}
{% endblock %}
{% block body %}
<!-- BREADCRUMB -->
<div id="breadcrumb">
	<div class="container">
		<ul class="breadcrumb">
			<li><a href="#">Home</a></li>
			<li class="active">Shopping Cart</li>
		</ul>
	</div>
</div>
<!-- /BREADCRUMB -->
{% if messages %} {% for message in messages %}
<div class="container">
	<div class="alert alert-{{ message.tags }}" role="alert" style="margin-top: 20px; margin-bottom: 0;">
		{{ message }}
	</div>
</div>
{% endfor %} {% endif %}

<!-- section -->
<div class="section" style="padding-top: 15px">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			<div class="col-md-12">
				<div class="order-summary clearfix">
					<div class="section-title">
						<h3 class="title">Order Review</h3>
					</div>
					<table class="shopping-cart-table table">
						<thead>
							<tr>
								<th>Product</th>
								<th>Name</th>
								<th class="text-center">Price</th>
								<th class="text-center">Quantity</th>
								<th class="text-center">Total</th>
								<th class="text-right"></th>
							</tr>
						</thead>
						<tbody>
							{% for basket in baskets %}
							<tr>
								<td class="thumb"><img src="{{ basket.product.image.url }}"></td>
								<td class="details"><a href="#">{{ basket.product.title }}</a></td>
								<td class="price text-center"><strong>${{ basket.price }}</strong></td>
								<td class="qty text-center">{{ basket.quantity }}</td>
								<td class="total text-center"><strong class="primary-color">${{ basket.amount }}</strong></td>
								<td class="text-right"><a href="{% url 'deletetobasket' basket.id %}" class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
							</tr>
							{% endfor %}
						</tbody>
						<tfoot>
							<tr>
								<th class="empty" colspan="3"></th>
								<th>TOTAL</th>
								<th colspan="2" class="total" id="total">$97.50</th>
							</tr>
						</tfoot>
					</table>
					<div class="pull-right">
						<a href="{% url 'orderproduct' %}" class="primary-btn">Place Order</a>
					</div>
				</div>
			</div>
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /section -->
<script>
	function basketTotalPrice() {
		var basketPrice = document.querySelectorAll(".total.text-center strong")
		var total = 0
		Array.from(basketPrice).forEach(e => total += Number(e.textContent.slice(1)))
		return total;
	}
	document.querySelector("#total").textContent = "$" + basketTotalPrice()
</script>
{% endblock %}